### ISSUE TITLE
Scaffolding for Website

### ISSUE THREAD

**Issue by GDWR** [GDWR/DiscordArena#2]
Decide on a framework for a website and scaffold it, 

I would like for the scaffolding to contain at least:
* one usage of the API
* two pages (Homepage and Login)

Functionality is not necessary atm, although the first functionality would be adding a way to login via your discord account

**Comment by DudeBro249** [comment]
Would we be using client side or server side rendering?

**Comment by GDWR** [comment]
Preferably client side rendering, but if you have a suggested framework. I wouldn't mind looking into it and seeing if I think it will fit nicely into this project.

Although everything so far is Python,
I do not think Python would be a good fit for the website. I would be up for having my mind changed

**Comment by DudeBro249** [comment]
I believe that server side rendering should be used for this web application(not necessarily python though). This is because if you want separate html descriptions or meta tags for, say, each user on website.com/users/GDWR(so you can have custom embeds and cards for content), then server side rendering is necessary. We can use libraries like [NextJS](https://nextjs.org/) which allows you to render react on the server once.

**Comment by GDWR** [comment]
I would like to discuss this further with you via voice, sounds good. :+1:
